# Site settings
title: TBD
header-img: img/home-bg.png
email: erin.v.doyle@gmail.com
copyright_name: erinvdoyle
description: > # this means to ignore newlines until "baseurl:"
  TBD
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  erinvdoyle
learn_profile: erinvdoyle
email_username: erin.v.doyle@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
